language: ruby
cache: bundler
rvm:
- 2.4.0
deploy:
  provider: heroku
  api_key:
    secure: OmM/3ZQ5KMEVZFbEzmB4X6RxcQcgNIS70L/s8kap/B0gi6M7Pjm1ty7393EBWm66k9Lw+J82UxDLnVb1tCf4QVFsQc+l7sFGLw11p8UJZXBIgziqXq+v/xTIxocjRA+PvSdIkV3PjBeZ0LKsYW7b+D+YawGO8TGvjUEjnq4KKY0=
  app: pokrovsky
  on:
    repo: pikesley/pokrovsky
