language: ruby
cache: bundler
rvm:
- 2.4.0
deploy:
  provider: heroku
  app: pokrovsky
  api_key:
    secure: "UyYdGrzj+3m/u5F20GCyfPFMJhAVq7v4FXJTYq4VLxGF7/13QpS76Ep9DBLZJb/GlRyfaRzi7IEr0pORItAYXTlg5yWBSOzyAmApT1G52JyevDtC0xeVdO5uAzZEgxfmgAIfFJLNSVVjMb8DwECG+noYoUO8AG0zBYFdpjNFslY="
